Blog app - integration specs for views and fix n+1 problems
Gmanlove/blog-app pull request #8
Opened 2023-06-19 22:25 UTC by Gmanlove

In this pull request ♻️

- [ ] Solve the N+1 problem when fetching in this URL (users/:id/posts) 👍

- [ ] Setup Capybara to write integration tests 👍

- [ ] write all required tests

![Screenshot 2023-06-19 at 14 04 20](https://github.com/Gmanlove/blog-app/assets/113697772/4b4f3a10-507f-4f8d-b80e-3b2f00507088)
![Screenshot 2023-06-19 at 14 01 46](https://github.com/Gmanlove/blog-app/assets/113697772/5b9d2ca4-1373-47ef-b326-33a9ec1f4940)

2023-06-19 23:12 UTC, Owusu-Desmond requested changes
Hi @Gmanlove and @belalgamal46 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
📌 Your linters are passing✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Your readme file is okay ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-19 23:12 UTC, Owusu-Desmond commented on spec/features/user_index_spec.rb
> +  end
- [ ] Good to have this user index test file. :+1:  But please from the project requirement, you should write a test for the following :point_down: But now you have no test code in your `it` block to test the following:blush: 
  
  -   Tests that asserts you can see the username of all other users.
  -   Tests that asserts you can see the profile picture for each user.
  -   Tests that asserts you can see the number of posts each user has written.
  -   Tests that redirects to the user's show page when you click on a user.

2023-06-19 23:12 UTC, Owusu-Desmond commented on spec/features/post_show_spec.rb
> +    # Test code goes here
- [ ] Good to have this post-show test file. :+1:  But please from the project requirement, you should write a test for the following :point_down: But now you have no test code in your `it` block to test the following:blush: 

  * Tests that asserts you can see the post's title.
  * Tests that asserts you can see who wrote the post.
  * Tests that asserts you can see how many comments it has.
  * Tests that asserts you can see how many likes it has.
  * Tests that asserts you can see the post body.
  * Tests that asserts you can see the username of each commentor.
  * Tests that asserts you can see the comment each commentor left.

2023-06-19 23:12 UTC, Owusu-Desmond commented on spec/features/user_show_spec.rb
> +end
- [ ] Good to have this user show test file. :+1:  But please from the project requirement, you should write a test for the following :point_down: But now you have no test code in your `it` block to test the following:blush: 
  
  * Tests that asserts you can see the user's profile picture.
  * Tests that asserts you can see the user's username.
  * Tests that asserts you can see the number of posts the user has written.
  * Tests that asserts you can see the user's bio.
  * Tests that asserts you can see the user's first 3 posts.
  * Tests that asserts you can see a button that lets me view all of a user's posts.
  * Tests that redirects to the post's show page when you click on a user's post.
  * Tests that redirects to the user's post's index page when you click on a **see all posts**.

2023-06-19 23:12 UTC, Owusu-Desmond commented on spec/features/user_post_index_spec.rb
> +  end
- [ ] Good to have this user post index test file. :+1:  But please from the project requirement, you should write a test for the following :point_down: But now you have no test code in your `it` block to test the following:blush: 
  
  * Tests that asserts you can see the user's profile picture.
  * Tests that asserts you can see the user's username.
  * Tests that asserts you can see the number of posts the user has written.
  * Tests that asserts you can see a post's title.
  * Tests that asserts you can see some of the post's body.
  * Tests that asserts you can see the first comments on a post.
  * Tests that asserts you can see how many comments a post has.
  * Tests that asserts you can see how many likes a post has.
  * Tests that asserts you can see a section for pagination if there are more posts than fit on the view.
  * Tests that redirects to the post's show page when you click on a post.

2023-06-22 16:41 UTC, KDlamini requested changes
### Hi team @Gmanlove, @belalgamal46 🙋‍♀️,  

You have done an incredible job implementing some of the changes requested by the previous reviewer. 👏🏾👏🏾👏🏾  
However, there are still some changes that aren't addressed yet. You are almost there! 💪🏾 

Highlights 🌞

✔️ Good PR title and description
✔️ Capybara and Rspec are used for tests
✔️ Tests for User and Posts pages are implemented

## Required Changes ♻️
 
**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

N/A

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-22 16:41 UTC, KDlamini commented on spec/features/post_index_spec.rb
Great job adding all the required specs 👏🏾💯

However, all your tests fail on my end.

![image](https://github.com/Gmanlove/blog-app/assets/38088818/95e147cb-1359-4fde-8ab7-566890363132)

- If the failing tests are due to an error on my system and they all pass on your end. Kindly reply with a screenshot of your passing tests. Thank you 🙏🏾

2023-06-22 17:13 UTC, Gmanlove commented on spec/features/post_index_spec.rb
You should have contacted me before returning for request changes....  All the test are passing at my end....  Now I have only one review left.....

2023-06-23 06:15 UTC, Gmanlove commented on spec/features/post_index_spec.rb
This is the Screenshot of my passing test. thanks 

- [ ] 
![Screenshot 2023-06-23 at 07 10 30](https://github.com/Gmanlove/blog-app/assets/113697772/3a7f4b1f-280a-4a01-834e-accfcb4c78ce)

2023-06-23 08:58 UTC, brytebee approved these changes
Hi, @Gmanlove 👋,

##

### Highlights💡
- Great updating the setup and seed.✔️
- Well-written tests.✔️
- All tests passed.✔️
- Good commit message.✔️ 
- Good PR Summary.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/fxsqOYnIMEefC/giphy.gif)

Good luck! 🎉 

##

###  **Optional Suggestions:**
Practice more about 
- the seeding of a database.
- use of capybara

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-23 14:37 UTC, merged